image: docker:dind
services:
  - docker:dind

variables:
  SPRING_PROFILES_ACTIVE: gitlab-ci
  DOCKER_DRIVER: overlay2

stages:
  - build
  - package
  - deploy

gradle-build:
  image: gradle:jdk8
  stage: build
  only:
    - master
  script: "gradle build"
  artifacts:
    paths:
      - scape-core-service/build/libs/*.jar

docker-build:
  stage: package
  only:
    - master
  script:
    - cd scape-core-service
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
#    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA