server:
  port: 4000

scape:
  service:
    subject:
      url: http://10.0.0.1:4001/api/v1/subjects
    degree:
      url: http://10.0.0.1:4002/api/v1/degrees

spring:
  application:
    name: core-service
  zipkin:
    base-url: http://10.0.0.1:9411/
  sleuth:
    sampler:
      probability: 1